name: Release Build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - run: pyinstaller --name "random-roll-call" --onefile --console manage.py
      - run: tar -czf random-roll-call-linux.tar.gz dist/random-roll-call
      - uses: softprops/action-gh-release@v2
        with:
          files: random-roll-call-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - run: pyinstaller --name "random-roll-call" --onefile --console manage.py
      - run: Compress-Archive -Path dist/random-roll-call.exe -DestinationPath random-roll-call-windows.zip
      - uses: softprops/action-gh-release@v2
        with:
          files: random-roll-call-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
